server:
  port=8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    #      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.springframework.jdbc.core: TRACE
